import algorithm, strutils, tables

var includes* = @["stdio.h"]

const headerName = ["complex.h",
                    "ctype.h",
                    "math.h",
                    "stdlib.h",
                    "string.h",
                    "time.h"]

var headers = initTable[string, seq[string]]()

headers["complex.h"] = @["cabs",
                         "carg",
                         "cacos",
                         "cacosh",
                         "casin",
                         "casinh",
                         "catan",
                         "catanh",
                         "ccos",
                         "ccosh",
                         "cexp",
                         "cfabs",
                         "cimag",
                         "clog",
                         "clog10",
                         "conj",
                         "cpow",
                         "cproj",
                         "creal",
                         "csin",
                         "csinh",
                         "csqrt",
                         "ctan",
                         "ctanh"] 

headers["ctype.h"] = @["isalnum",
                       "isalpha",
                       "iscntrl",
                       "isdigit",
                       "isgraph",
                       "islower",
                       "isprint",
                       "ispunct",
                       "isspace",
                       "isupper",
                       "isxdigit",
                       "tolower",
                       "toupper"]

headers["math.h"] = @["acos",
                      "asin",
                      "atan",
                      "atan2",
                      "ceil",
                      "cos",
                      "cosh",
                      "exp",
                      "fabs",
                      "floor",
                      "fmod",
                      "frexp",
                      "ldexp",
                      "log",
                      "log10",
                      "modf",
                      "pow",
                      "sin",
                      "sinh",
                      "sqrt",
                      "tan",
                      "tanh"]
  
headers["stdlib.h"] = @["abort",
                        "abs",
                        "atexit",
                        "atof",
                        "atoi",
                        "atol",
                        "bsearch",
                        "calloc",
                        "div",
                        "exit",
                        "free",
                        "getenv",
                        "labs",
                        "ldiv",
                        "malloc",
                        "mblen",
                        "mbstowcs",
                        "mbtowc",
                        "qsort",
                        "rand",
                        "realloc",
                        "srand",
                        "strtod",
                        "strtol",
                        "strtoul",
                        "system",
                        "wcstombs",
                        "wctomb"]

headers["string.h"] = @["memchr",
                        "memcmp",
                        "memcpy",
                        "memmove",
                        "memset",
                        "strchr",
                        "strcat",
                        "strcmp",
                        "strcpy",
                        "strcspn",
                        "strerror",
                        "strcoll",
                        "strlen",
                        "strncat",
                        "strncmp",
                        "strncpy",
                        "strpbrk",
                        "strrchr",
                        "strspn",
                        "strstr",
                        "strtok",
                        "strxfrm"]

headers["time.h"] = @["clock_t",
                      "time_t",
                      "struct",
                      "CLOCKS_PER_SEC",
                      "asctime",
                      "clock",
                      "ctime",
                      "difftime",
                      "gmtime",
                      "localtime",
                      "mktime",
                      "strftime",
                      "time"]

proc autoInclude*(funcName: string) =
  for hname in headerName:
    if headers[hname].binarySearch(funcName) >= 0:
      if includes.binarySearch(hname) < 0:
        includes.add(hname)
      break
